CFLAGS = -std=gnu11 -Wall -Wextra -lm -g 

.PHONY: all
all: hadamard1 hadamard2

.PHONY: clean
clean:
	$(RM) hadamard1 hadamard2
	rm -r results 

hadamard1: hadamard1.c

hadamard2: hadamard2.c
